name: 'autoupdate-branch'
description: 'Update PRs with particular label'
branding:
  icon: 'arrow-down-circle'  
  color: 'gray-dark'

inputs:
  repo-token:
    description: 'Token of repo'
    required: true
  label:
    description: 'Action will update branches with this label'
    required: true
  updateAllPullRequest:
    description: 'Flag setting if every pr (even which auto merge is not enabled) should be updated'
    required: false
  requiredApprovals:
    description: 'Number of required approvals before branch should be updated'
    required: false
  requiredPassedChecks:
    description: 'Flag setting if checks should passed before branch should be updated'
    required: false
  update-limits:
    description: 'Number of branches which should be updated in one run'
    required: false

outputs:
  hasConflicts:
    description: 'Says if PR is conflicted'
  conflictedPullRequestJSON:
    description: 'data of conflicted PR in JSON in shape {title: string, url: string, user: {login, url, avatarUrl}}'

runs:
  using: 'node12'
  main: 'dist/index.js'
